export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS';
export const GET_TASKS_PENDING = 'GET_TASKS_PENDING';
export const GET_TASKS_ERROR = 'GET_TASKS_ERROR';

export const DELETE_TASKS_SUCCESS = 'DELETE_TASKS_SUCCESS';
export const DELETE_TASKS_PENDING = 'DELETE_TASKS_PENDING';
export const DELETE_TASKS_ERROR = 'DELETE_TASKS_ERROR';

export const ADD_TASKS_SUCCESS = 'ADD_TASKS_SUCCESS';
export const ADD_TASKS_PENDING = 'ADD_TASKS_PENDING';
export const ADD_TASKS_ERROR = 'ADD_TASKS_ERROR';

export const EDIT_TASKS_SUCCESS = 'EDIT_TASKS_SUCCESS';
export const EDIT_TASKS_PENDING = 'EDI_TASKS_PENDING';
export const EDIT_TASKS_ERROR = 'EDIT_TASKS_ERROR';
