export const GET_ADMINS_SUCCESS = 'GET_ADMINS_SUCCESS';
export const GET_ADMINS_PENDING = 'GET_ADMINS_PENDING';
export const GET_ADMINS_ERROR = 'GET_ADMINS_ERROR';

export const DELETE_ADMINS_SUCCESS = 'DELETE_ADMINS_SUCCESS';
export const DELETE_ADMINS_PENDING = 'DELETE_ADMINS_PENDING';
export const DELETE_ADMINS_ERROR = 'DELETE_ADMINS_ERROR';

export const ADD_ADMINS_SUCCESS = 'ADD_ADMINS_SUCCESS';
export const ADD_ADMINS_PENDING = 'ADD_ADMINS_PENDING';
export const ADD_ADMINS_ERROR = 'ADD_ADMINS_ERROR';

export const EDIT_ADMINS_SUCCESS = 'EDIT_ADMINS_SUCCESS';
export const EDIT_ADMINS_PENDING = 'EDIT_ADMINS_PENDING';
export const EDIT_ADMINS_ERROR = 'EDIT_ADMINS_ERROR';

export const CLEAN_ADMINS_ERROR = 'CLEAN_ADMINS_ERROR';
